version: "3.8"

services:
  api:
    build: ./app
    container_name: fastapi-backend
    ports:
      - "8000:8000" # Expose directly for testing
    volumes:
      - ./app:/app/app
      - huggingface_cache:/home/app/.cache/huggingface
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - DATA_DIR=/app/data
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SARVAM_API_KEY=${SARVAM_API_KEY}
      - WAVES_API_KEY=${WAVES_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - HF_HOME=/home/app/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/app/.cache/huggingface/transformers
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - PORT=8000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 512M
  frontend:
    build: ./voice-agent-portal
    container_name: react-frontend
    volumes:
      - frontend_build:/usr/share/nginx/html
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - api
      - frontend

volumes:
  # external: true
  # name: voice_agent_data
  huggingface_cache:
  frontend_build:
